env:
  global:
  - CATALOG_IMAGE_REPO=quay.io/tqvarnst/catalog-native

cache:
  directories:
  - $HOME/.m2

services:
  - docker

language: java

jdk:
  - oraclejdk8

before_install:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" quay.io
  - cp .travis.settings.xml $HOME/.m2/settings.xml

script:
  - pushd catalog
  - mvn clean package -Pnative
  - docker build -t catalog-native .
  - docker tag catalog-native:latest $CATALOG_IMAGE_REPO:latest
  - popd

