env:
  global:
  - CATALOG_IMAGE_REPO=quay.io/tqvarnst/catalog-native
  - GRAALVM_HOME=$HOME/graalvm-ce-1.0.0-rc12

cache:
  directories:
  - $HOME/.m2

services:
  - docker

language: java

jdk:
  - oraclejdk8

before_install:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" quay.io
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - curl -LO https://github.com/oracle/graal/releases/download/vm-1.0.0-rc12/graalvm-ce-1.0.0-rc12-linux-amd64.tar.gz
  - tar -zxvf graalvm-ce-1.0.0-rc12-linux-amd64.tar.gz -C $HOME/

script:
  - pushd catalog
  - mvn clean package -Pnative -DskipTests && docker build -t catalog-native . && docker tag catalog-native:latest $CATALOG_IMAGE_REPO:latest && docker push $CATALOG_IMAGE_REPO:latest
  - popd

